# Generated by Django 5.1.1 on 2025-01-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo',
            new_name='Todo2',
        ),
        migrations.RenameField(
            model_name='todo2',
            old_name='todo_text',
            new_name='title',
        ),
    ]
