# Generated by Django 5.1.1 on 2024-12-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event2',
            old_name='event2_text',
            new_name='title',
        ),
    ]
