# Generated by Django 5.1.1 on 2025-01-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event2', '0002_rename_event2_text_event2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
